# Generated by Django 6.0.5 on 2026-05-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
