# Generated by Django 6.0.5 on 2026-05-25 07:39

import todo_item.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_item', '0002_alter_todoitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(max_length=100, validators=[todo_item.models.check_empty_title_or_description]),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=50, validators=[todo_item.models.check_empty_title_or_description]),
        ),
    ]
