# Generated by Django 6.0.5 on 2026-05-25 07:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_item', '0005_alter_todoitem_description_alter_todoitem_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, 'Title cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[django.core.validators.MinLengthValidator(1, 'Description cannot be empty')]),
        ),
    ]
