# Generated by Django 6.0.5 on 2026-05-25 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_item', '0006_alter_todoitem_description_alter_todoitem_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='todoitem',
            constraint=models.CheckConstraint(condition=models.Q(('title__length__gte', 1), ('description__length__gte', 1)), name='title_and_description_not_empty'),
        ),
    ]
